### ISSUE TITLE
Method StatisticFunctions::stdev returns wrong results when small numbers are provided

### ISSUE THREAD

**Issue by silencersm** [LupeCode/phpTraderNative#1]
Hello Lupe and thanks for this awesome TA-Lib.
I was experimenting using it and noticed that the Trader::bbands method was returning wrong results when supplied with relatively small numbers. I am using binance data so for example the figures will be of the form "0.00004300".
I have looked into it and it seems that the C implementation is suffering from the same issue.
I noticed that it works correct by commenting out the if statement code in the lines below in the links so only code in lines 493 and 502 will be executed respectively.
 https://github.com/LupeCode/phpTraderNative/blob/d9902815d8be01d27ad3725bb1c77b71fdbf2e3b/source/TALib/Core/StatisticFunctions.php#L492
https://github.com/LupeCode/phpTraderNative/blob/d9902815d8be01d27ad3725bb1c77b71fdbf2e3b/source/TALib/Core/StatisticFunctions.php#L501

I have attached a screenshot of the commented code.
![screenshot from 2018-08-06 23-05-24](https://user-images.githubusercontent.com/3285189/43743356-56e8ca2c-99cd-11e8-808e-ce53cbd2dc0e.png)

I was wondering if you could test that and provide a fix
Thanks again for you time and I am happy to contact me for any further clarification needed

**Comment by jb-lopez** [comment]
That is very interesting.  I'm curious as to why the original authors were avoiding performing a square root on a very small number.  Maybe there was a limit in one of their C compilers or targets?

Whatever their reason, the problem they were trying to avoid does not seem to be a problem in PHP.

I see no reason to not make this change.  Version 1.0.4 has the fix you requested.

Thank you for taking the time to let me know about this bug.
