### ISSUE TITLE
EMA Error

### ISSUE THREAD

**Issue by MixMe** [LupeCode/phpTraderNative#16]
Hi, thank for cool extension, any Idea about this error?

![Screenshot 2023-09-18 at 18 47 41](https://github.com/LupeCode/phpTraderNative/assets/3535911/c58ebf02-99e0-473e-af39-6aa52b7af086)

**Comment by MixMe** [comment]
same problem with RSI:
Undefined array key 20 in /app/vendor/lupecode/php-trader-native/source/TALib/Core/Lookback.php:1163

this error appears after updating from v1 to v2

**Comment by jb-lopez** [comment]
Thanks for reporting the error @MixMe 

Could you provide the input you were using that gave the error? My testing data doesn't generate any so it must not be comprehensive enough.

**Comment by MixMe** [comment]
![Screenshot 2023-09-19 at 09 58 48](https://github.com/LupeCode/phpTraderNative/assets/3535911/b7c3b5c5-5811-4bcb-985b-91c8c4d6bf30)

here $optInTimePeriod is: 
14 

static:$unstablePeriod is:
[
    0 => 0
    1 => 0
]

Input:

`[
    0 => '26085.51000000'
    1 => '26076.00000000'
    2 => '26091.99000000'
    3 => '26088.44000000'
    4 => '26069.87000000'
    5 => '26074.51000000'
    6 => '26090.31000000'
    7 => '26112.00000000'
    8 => '26119.55000000'
    9 => '26108.00000000'
    10 => '26111.98000000'
    11 => '26144.00000000'
    12 => '26148.70000000'
    13 => '26136.10000000'
    14 => '26131.77000000'
    15 => '26148.05000000'
    16 => '26165.78000000'
    17 => '26145.84000000'
    18 => '26158.04000000'
    19 => '26176.70000000'
    20 => '26153.52000000'
    21 => '26140.38000000'
    22 => '26189.09000000'
    23 => '26183.72000000'
    24 => '26176.35000000'
    25 => '26172.00000000'
    26 => '26174.31000000'
    27 => '26135.90000000'
    28 => '26144.01000000'
    29 => '26139.09000000'
    30 => '26110.16000000'
    31 => '26062.87000000'
    32 => '26070.41000000'
    33 => '26061.91000000'
    34 => '26055.99000000'
    35 => '26106.83000000'
    36 => '26087.59000000'
    37 => '26089.77000000'
    38 => '26062.36000000'
    39 => '26053.01000000'
    40 => '26077.18000000'
    41 => '26085.78000000'
    42 => '26130.00000000'
    43 => '26124.18000000'
    44 => '26142.01000000'
    45 => '26144.01000000'
    46 => '26125.04000000'
    47 => '26113.81000000'
    48 => '26109.02000000'
    49 => '26132.48000000'
    50 => '26122.29000000'
    51 => '26137.25000000'
    52 => '26188.16000000'
    53 => '26166.78000000'
    54 => '26264.42000000'
    55 => '26232.98000000'
    56 => '26166.00000000'
    57 => '26201.58000000'
    58 => '26171.05000000'
    59 => '26176.86000000'
    60 => '26196.01000000'
    61 => '26209.27000000'
    62 => '26188.96000000'
    63 => '26209.46000000'
    64 => '26152.00000000'
    65 => '26177.29000000'
    66 => '26186.01000000'
    67 => '26189.99000000'
    68 => '26133.37000000'
    69 => '26121.86000000'
    70 => '26144.40000000'
    71 => '26142.00000000'
    72 => '26110.00000000'
    73 => '26156.01000000'
    74 => '26147.70000000'
    75 => '26146.14000000'
    76 => '26153.76000000'
    77 => '26120.01000000'
    78 => '26084.00000000'
    79 => '26097.38000000'
    80 => '26094.87000000'
    81 => '26107.10000000'
    82 => '26084.77000000'
    83 => '26090.66000000'
    84 => '26073.36000000'
    85 => '26060.77000000'
    86 => '26055.01000000'
    87 => '26059.02000000'
    88 => '26071.41000000'
    89 => '26137.91000000'
    90 => '26116.01000000'
    91 => '26104.54000000'
    92 => '26087.50000000'
    93 => '26103.00000000'
    94 => '26073.99000000'
    95 => '26032.00000000'
    96 => '26033.99000000'
    97 => '26004.75000000'
    98 => '26033.99000000'
    99 => '26023.34000000'
    100 => '26015.45000000'
    101 => '26069.62000000'
    102 => '26047.99000000'
    103 => '26059.99000000'
    104 => '26081.00000000'
    105 => '26064.00000000'
    106 => '26038.01000000'
    107 => '26028.00000000'
    108 => '25972.41000000'
    109 => '25972.16000000'
    110 => '25965.11000000'
    111 => '25944.01000000'
    112 => '25942.94000000'
    113 => '25957.99000000'
    114 => '26000.87000000'
    115 => '26031.60000000'
    116 => '26080.75000000'
    117 => '26050.07000000'
    118 => '26050.59000000'
    119 => '26004.00000000'
    120 => '25998.01000000'
    121 => '26014.98000000'
    122 => '26045.29000000'
    123 => '26129.70000000'
    124 => '26110.49000000'
    125 => '26062.00000000'
    126 => '26110.41000000'
    127 => '26108.51000000'
    128 => '26035.39000000'
    129 => '25866.36000000'
    130 => '25946.01000000'
    131 => '25939.59000000'
    132 => '25950.88000000'
    133 => '26004.01000000'
    134 => '25986.66000000'
    135 => '26015.43000000'
    136 => '26016.65000000'
    137 => '26064.63000000'
    138 => '26058.00000000'
    139 => '26050.70000000'
    140 => '26065.29000000'
    141 => '26055.09000000'
    142 => '26061.16000000'
    143 => '26034.18000000'
    144 => '26076.01000000'
    145 => '26045.44000000'
    146 => '26118.00000000'
    147 => '26097.74000000'
    148 => '26109.98000000'
    149 => '26106.00000000'
    150 => '26091.44000000'
    151 => '26105.60000000'
    152 => '26093.65000000'
    153 => '26118.29000000'
    154 => '26199.99000000'
    155 => '26196.01000000'
    156 => '26166.99000000'
    157 => '26161.99000000'
    158 => '26143.07000000'
    159 => '26132.00000000'
    160 => '26140.00000000'
    161 => '26124.00000000'
    162 => '26139.51000000'
    163 => '26126.92000000'
    164 => '26132.01000000'
    165 => '26102.25000000'
    166 => '26106.10000000'
    167 => '26100.11000000'
    168 => '26062.34000000'
    169 => '26066.19000000'
    170 => '26065.20000000'
    171 => '26050.00000000'
    172 => '26058.00000000'
    173 => '26060.43000000'
    174 => '26066.96000000'
    175 => '26065.61000000'
    176 => '26048.17000000'
    177 => '26031.27000000'
    178 => '26040.86000000'
    179 => '26055.99000000'
    180 => '26033.91000000'
    181 => '26028.55000000'
    182 => '26018.70000000'
    183 => '26015.22000000'
    184 => '26031.32000000'
    185 => '26036.00000000'
    186 => '26036.01000000'
    187 => '26041.39000000'
    188 => '26060.02000000'
    189 => '26060.01000000'
    190 => '26042.00000000'
    191 => '26069.99000000'
    192 => '26077.44000000'
    193 => '26079.59000000'
    194 => '26117.00000000'
    195 => '26106.69000000'
    196 => '26110.42000000'
    197 => '26099.55000000'
    198 => '26076.00000000'
    199 => '26061.72000000'
]`

**Comment by jb-lopez** [comment]
@MixMe what version of PHP are you using? `static:$unstablePeriod` should have 23 entries, but yours has two. My first thought is that the switch to using enums is to blame here, but it should work as long as you are using PHP 8.1+.

https://github.com/LupeCode/phpTraderNative/blob/f6d8387d1b0e758574c08c6c31f774cfb7faae77/source/TALib/Core/Core.php#L99

This is where the array is populated. v2 is using [enumerations](https://www.php.net/manual/en/language.enumerations.php).

**Comment by MixMe** [comment]
I use PHP Version 8.2.10

**Comment by MixMe** [comment]
UnstablePeriodFunctionID::cases()   return empty array

**Comment by jb-lopez** [comment]
Oh. How odd that it is working for me, but I can investigate that later.

That fix is easy enough. If you would like credit for it go ahead and make a pull request. If not I can make the change.

**Comment by MixMe** [comment]
@jb-lopez  "static::$unstablePeriod" must contain:
`[ 0 => 0 1 => 0 2 => 0 3 => 0 4 => 0 5 => 0 6 => 0 7 => 0 8 => 0 9 => 0 10 => 0 11 => 0 12 => 0 13 => 0 14 => 0 15 => 0 16 => 0 17 => 0 18 => 0 19 => 0 20 => 0 21 => 0 22 => 0 ]`

??

**Comment by MixMe** [comment]
Yes i can do it

**Comment by MixMe** [comment]
Hi @jb-lopez , how can I upload my changes?
