### ISSUE TITLE
Fatal error using plusDI and minusDI

### ISSUE THREAD

**Issue by pottertech** [LupeCode/phpTraderNative#17]
I am getting the following errors:
for minusDI
PHP Fatal error:  Uncaught ErrorException: Undefined array key 15 in /root/vendor/lupecode/php-trader-native/source/TALib/Core/MomentumIndicators.php:1164

for plusDI
PHP Fatal error:  Uncaught ErrorException: Undefined array key 18 in /root/vendor/lupecode/php-trader-native/source/TALib/Core/MomentumIndicators.php:1466

I did a little debugging with var_dump:

code: var_dump( static::$unstablePeriod );
results:
array(2) {
  [0]=>
  int(0)
  [1]=>
  int(0)
}

code: var_dump( UnstablePeriodFunctionID::MinusDI] );
results:
int(15)

I am using PHP 8.2.12. Any help is greatly appreciated.

**Comment by jb-lopez** [comment]
I did find an issue in Packagist, it did not have v2.0.1, which should fix this issue.

Can you verify that you are using v2.0.1? If not can you update and check that the error is fixed?

**Comment by jb-lopez** [comment]
I'm going to assume that you used composer to install this library. Running `composer show` will tell you the version of all the installed packages. Running `composer update` will update them.

**Comment by pottertech** [comment]
OK, I updated the composer.json file and did the composer update and all is well.  Thanks.
