### ISSUE TITLE
stochrsi testing

### ISSUE THREAD

**Issue by jb-lopez** [LupeCode/phpTraderNative#3]
The stochrsi fails to compare with trading view.

Test the functions involved and compare the results with hand generated numbers.

- [x] Test the stoch function
- [x] Test the rsi function
- [x] Test stochrsi vs stoch and rsi
- [x] Test stochrsi
- [x] Test a slow stochrsi; does not exist in ta-lib

**Comment by sixcom** [comment]
I have tested stoch and rsi a few times, they seem good

**Comment by jb-lopez** [comment]
Tested rsi with hand-generated data in 5449e15a7e434137560c3d6e33c343e1f0258ab2 
Tested stoch with hand-generated data in f8b958199a083296657bcdf48e23afc54b2b1985 
Tested stochrsi vs stoch and rsi with hand-generated data in 9f0affbffe1a1f9b312f2fd5a0ec4038f3a3c068 
Tested stochrsi with hand-generated data in 1c5e69f6463383a733e98d5c94123aa28cf754ae 

All of the tests pass.

**Comment by jb-lopez** [comment]
I've added a slow stoch rsi function.  I've also tested it compared to TV, and the numbers match up.

The commit is 990ed8214a0c61960d658c29847211c799a17a13 

The function is `LupeTrader::slowstochrsi`
