### ISSUE TITLE
ADX Indicator wrong results

### ISSUE THREAD

**Issue by gnsimoes** [LupeCode/phpTraderNative#4]
Hello,

I am exploring the phpTraderNative in a Symfony 4.2 project, but I am having problems to get the right results using the ADX indicator.
Could you help me on that issue, or do you have any kind configuration or workaround?

Thanks,

**Comment by jb-lopez** [comment]
@gnsimoes,

Thank you for letting me know.

Do you happen to have a set of data, numbers in and numbers expected out?  If you can let me know the results you were expecting, I can troubleshoot better.

I would like to apologize for not responding sooner.

**Comment by jb-lopez** [comment]
@gnsimoes I'm going to close this issue, as it has been just over a year and I've not heard back. Without the details about how it is wrong, I cannot begin to troubleshoot.

However, the goal of this project is to provide the functions available in the Trader PECL extension without installing the extension. The ADX functions output matches that of the PECL Trader, which means that if there is a bug it is in the PECL extension, or in TA-Lib directly.

If you do get back with more details, I can get a fix in for this library and work with the maintainers of PECL Trader and TA-Lib to get the fix back-ported into the C code as well.
