### ISSUE TITLE
Bump ext-trader to 0.5?

### ISSUE THREAD

**Issue by yazeed** [LupeCode/phpTraderNative#7]
Hi, thanks for sharing this library, I was wondering if you are able to bump the ext-trader to 0.5, or if you purposefully chose to go with 0.4 instead?

**Comment by jb-lopez** [comment]
I've done some testing and updated the ext-trader version to >= 0.4.1. The only difference between 0.4.1 and 0.5 is that 0.5 is faster for PHP 7.

I'd like to keep the usable versions to as many as possible.

Besides, you only need ext-trader if you are modifying this package and want to run the tests.
